//Assignment 20 :

class HelicopterRunner {

public static void main(String[] args)
{
System.out.println("Start in HelicopterRunner");
Helicopter ref=new Helicopter();
Helicopter ref1=new Helicopter();
new Helicopter();
new Helicopter();
new Helicopter();
System.out.println("----------------------------------");
Market value=new Market();
Market name=new Market();
new Market();
new Market();
new Market();
System.out.println("----------------------------------");
Mall ref2=new Mall();
Mall ref3=new Mall();
new Mall();
new Mall();
new Mall();
System.out.println("----------------------------------");
Train game=new Train();
Train names=new Train();
new Train();
new Train();
new Train();
System.out.println("----------------------------------");
Ring game1=new Ring();
Ring names1=new Ring();
new Ring();
new Ring();
new Ring();
System.out.println("----------------------------------");
Auto play=new Auto();
Auto rest=new Auto();
new Auto();
new Auto();
new Auto();
System.out.println("----------------------------------");
Auditorium play1=new Auditorium();
Auditorium rest2=new Auditorium();
new Auditorium();
new Auditorium();
new Auditorium();
System.out.println("----------------------------------");
SpaceShip mirror=new SpaceShip();
SpaceShip cloth=new SpaceShip();
new SpaceShip();
new SpaceShip();
new SpaceShip();
System.out.println("----------------------------------");
Alien mirror1=new Alien();
Alien cloth1=new Alien();
new Alien();
new Alien();
new Alien();
System.out.println("----------------------------------");
Bullet range=new Bullet();
Bullet dress=new Bullet();
new Bullet();
new Bullet();
new Bullet();
System.out.println("----------------------------------");
Galaxy range1=new Galaxy();
Galaxy dress1=new Galaxy();
new Galaxy();
new Galaxy();
new Galaxy();
System.out.println("----------------------------------");
Spoon food=new Spoon();
Spoon cofee=new Spoon();
new Spoon();
new Spoon();
new Spoon();
System.out.println("----------------------------------");
BlackHole pen=new BlackHole();
BlackHole pencil=new BlackHole();
new BlackHole();
new BlackHole();
new BlackHole();
System.out.println("----------------------------------");
Cake sweet=new Cake();
Cake sugar=new Cake();
new Cake();
new Cake();
new Cake();
System.out.println("----------------------------------");
Wrapper cake=new Wrapper();
Wrapper puffs=new Wrapper();
new Wrapper();
new Wrapper();
new Wrapper();
System.out.println("Ends in HelicopterRunner");
}
}